### ISSUE TITLE
Gradle Wrapper Validation Action fails

### ISSUE THREAD

**Issue by hfhbd** [cy6erGn0m/kotlinx-uuid#5]
Hey, 
After adding the GitHub Action to validate the Gradle Wrapper (#4), it is still not running, because only contributors are allow to create or modify GitHub Actions. 
Sorry, I did not know this.
I guess, deleting and recommitting the workflow file should be enough.

**Comment by cy6erGn0m** [comment]
It didn't work because of too strict policy I've configured for the repo. Fixed by allowing this particular action.
