### ISSUE TITLE
Add JVM IR Support

### ISSUE THREAD

**Issue by hfhbd** [cy6erGn0m/kotlinx-uuid#6]
Is it possible to publish non-IR and IR JVM artifacts?

**Comment by cy6erGn0m** [comment]
JVM IR backend is highly experimental. What is the reason to include it?

**Comment by hfhbd** [comment]
Simply to test the compatibility with other JVM-IR preview libraries, especially (Android) Jetpack Compose

**Comment by cy6erGn0m** [comment]
Ok, let's try it in 0.0.2. Btw, I finally published 0.0.1 to a separate Bintray repo.

**Comment by hfhbd** [comment]
Thank you for the initial release!

**Comment by hfhbd** [comment]
Default with `1.5.0`
